server:
  port: 7002
  servlet:
    context-path: /ad-binlog-kafka

spring:
  application:
    name: eureka-client-ad-binlog-kafka
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jieming_ad_data?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  kafka:
    bootstrap-servers: 101.132.243.102:9092
    listener:
      concurrency: 4


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

adconf:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: 123456
    binlogName:
    position: -1

  kafka:
    topic: ad-search-mysql-data